vars: {
  d2-config: {
    layout-engine: dagre
    theme-id: 0
  }
}

DData: {
  shape: sql_table
  pk_tempo: int {constraint: primary_key}
  data: date
  dia: int
  mes: int
  ano: int
  trimestre: int
  semestre: int
  estacao: varchar
  semana_epidemiologica: int
}

DPaciente: {
  shape: sql_table
  pk_paciente: int {constraint: primary_key}
  idade: int
  ano_nascimento: int
  grupo_risco: varchar
}

DDemografia: {
  shape: sql_table
  pk_demografia: int {constraint: primary_key}
  faixa_etaria: varchar
  sexo: varchar
  raca_cor: varchar
  escolaridade: varchar
  gestante: varchar
}

DTipo_Notificacao: {
  shape: sql_table
  pk_tipo_notificacao: int {constraint: primary_key}
  flag_obito: bool
  flag_hospitalizacao: bool
  num_estado: int
  descricao_estado: varchar
}

DSinal_Clinico: {
  shape: sql_table
  pk_sinal_clinico: int {constraint: primary_key}
  cefaleia: bool
  mialgia: bool
  vomito: bool
  nausea: bool
  febre: bool
  dor_retro: bool
}

DLocal: {
  shape: sql_table
  pk_local: int {constraint: primary_key}
  municipio_id: int
  mesorregiao_nome: varchar
  municipio_nome: varchar
  microrregiao_nome: varchar
  populacao_municipio: int
  populacao_mesorregiao: int
  populacao_microrregiao: int
}

FNotificacao: {
  shape: sql_table
  pk_notificacao: int {constraint: primary_key}
  fk_data: int {constraint: foreign_key}
  fk_demografia: int {constraint: foreign_key}
  fk_paciente: int {constraint: foreign_key}
  fk_local_notificacao: int {constraint: foreign_key}
  fk_local_residencia: int {constraint: foreign_key}
  fk_tipo_notificacao: int {constraint: foreign_key}
  fk_sinal_clinico: int {constraint: foreign_key}
  fk_notificacao: int {constraint: foreign_key}
}

FNotificacao.fk_tipo_notificacao -> DTipo_Notificacao.pk_tipo_notificacao: {
  source-arrowhead.label: (1,1)
  target-arrowhead.label: (1,N)
}

FNotificacao.fk_sinal_clinico -> DSinal_Clinico.pk_sinal_clinico: {
  source-arrowhead.label: (1,1)
  target-arrowhead.label: (1,N)
}

FNotificacao.fk_data -> DData.pk_tempo: {
  source-arrowhead.label: (1,1)
  target-arrowhead.label: (1,N)
}

FNotificacao.fk_paciente -> DPaciente.pk_paciente: {
  source-arrowhead.label: (1,1)
  target-arrowhead.label: (1,N)
}

FNotificacao.fk_demografia -> DDemografia.pk_demografia: {
  source-arrowhead.label: (1,1)
  target-arrowhead.label: (1,N)
}

FNotificacao.fk_local_notificacao -> DLocal.pk_local: {
  source-arrowhead.label: (1,1)
  target-arrowhead.label: (1,N)
}

FNotificacao.fk_local_residencia -> DLocal.pk_local: {
  source-arrowhead.label: (1,1)
  target-arrowhead.label: (1,N)
}
