vars: {
  d2-config: {
    layout-engine: dagre
    theme-id: 0
  }
}

DTempo: {
  shape: sql_table
  pk_tempo: int {constraint: primary_key}
  data: date
  dia: int
  mes: int
  ano: int
  trimestre: int
  dia_semana: int
  fim_de_semana: bool
}



DHospede: {
  shape: sql_table
  pk_hospede: int {constraint: primary_key}
  cod_hospede_origem: varchar
  nome: varchar
  sexo: char(1)
  profissao: varchar
  pais: varchar
  uf: char(2)
  cidade: varchar
}

# Atributos a serem reavaliados:
#       Tipo da cama é relevante?
#       Cama de casal é importante?

DApartamento: {
  shape: sql_table
  pk_apartamento: int {constraint: primary_key}
  # cod_apartamento_origem: varchar
  numero_apartamento: varchar
  nome_tipo_apartamento: varchar
  andar: varchar
  # bloco: varchar(10)
}

# Comentei alguns atributos

DTipoServico: {
  shape: sql_table
  pk_servico: int {constraint: primary_key}
  cod_servico_origem: varchar
  nome_servico: varchar
  # categoria_servico: varchar
  # unidade: varchar
  # ativo: char
}

FServico: {
  shape: sql_table
  id_servico_fato: bigint {constraint: primary_key}
  id_tempo: int {constraint: foreign_key}
  id_hospede: int {constraint: foreign_key}
  id_apartamento: int {constraint: foreign_key}
  id_servico: int {constraint: foreign_key}
  pk_forma_pagto: int {constraint: foreign_key}
  quantidade: decimal(10,2)
  valor_unitario: decimal(12,2)
  valor_total_servico: decimal(14,2)
  valor_liquido: decimal(14,2)
  # nro_comanda: varchar(30)
  # nro_hospedagem: varchar(30)
}

FServico.id_tempo -> DTempo.id_tempo
FServico.id_hospede -> DHospede.id_hospede
FServico.id_apartamento -> DApartamento.id_apartamento
FServico.id_servico -> DTipoServico.pk_servico
