vars: {
  d2-config: {
    layout-engine: dagre
    theme-id: 0
  }
}

DTempo: {
  shape: sql_table
  pk_tempo: int {constraint: primary_key}
  data: date
  dia: int
  mes: int
  ano: int
  trimestre: int
  dia_semana: int
  fim_de_semana: bool
}

DCliente: {
  shape: sql_table
  pk_cliente: int {constraint: primary_key}
  cod_hospede_origem: varchar
  nome: varchar
  sexo: char(1)
  profissao: varchar
  pais: varchar
  uf: char(2)
  cidade: varchar
}

# Atributos a serem reavaliados:
#       Tipo da cama é relevante?
#       Cama de casal é importante?

DApartamento: {
  shape: sql_table
  pk_apartamento: int {constraint: primary_key}
  # cod_apartamento_origem: varchar
  numero_apartamento: varchar
  nome_tipo_apartamento: varchar
  andar: varchar
  # bloco: varchar(10)
}

# Comentei alguns atributos

DTipoServico: {
  shape: sql_table
  pk_tipo_servico: int {constraint: primary_key}
  cod_servico_origem: varchar
  nome_servico: varchar
  indicador_cobranca: int # ?
  # categoria_servico: varchar
  # unidade: varchar
  # ativo: char
}

FServico: {
  shape: sql_table
  pk_servico: bigint {constraint: primary_key}
  pk_tempo: int {constraint: foreign_key}
  pk_cliente: int {constraint: foreign_key}
  pk_apartamento: int {constraint: foreign_key}
  pk_tipo_servico: int {constraint: foreign_key}
  pk_consumo: int {constraint: foreign_key}
  valor_total: decimal
  valor_total_produtos: decimal
  quantidade_total_produtos: decimal
  # valor_liquido: decimal
  # nro_comanda: varchar
  # nro_hospedagem: varchar(30)
}

PonteConsumo: {
  shape: sql_table
  pk_consumo: int {constraint: primary_key}
  quantidade_produto: int
}

DProduto: {
  shape: sql_table
  pk_produto: int {constraint: primary_key}
  descricao: varchar
  valor_unitario: decimal
}


FServico.pk_tempo -> DTempo.pk_tempo: {
    source-arrowhead.label: (1,1)
    target-arrowhead.label: (1,N)
}
FServico.pk_cliente -> DCliente.pk_cliente: {
    source-arrowhead.label: (1,1)
    target-arrowhead.label: (1,N)
}
FServico.pk_apartamento -> DApartamento.pk_apartamento: {
    source-arrowhead.label: (1,1)
    target-arrowhead.label: (1,N)
}
FServico.pk_tipo_servico -> DTipoServico.pk_tipo_servico: {
    source-arrowhead.label: (1,1)
    target-arrowhead.label: (1,N)
}
FServico.pk_consumo -> PonteConsumo.pk_consumo: {
    source-arrowhead.label: (1,1)
    target-arrowhead.label: (1,N)
}
DProduto.pk_produto -> PonteConsumo.pk_produto: {
    source-arrowhead.label: (1,1)
    target-arrowhead.label: (1,N)
}
